services:
  jupyterhub:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - JUPYTERHUB_CONFIG=./app/jupyterhub_config.py
    restart: unless-stopped
