version: '3.8'

services:
  jupyterhub:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - JUPYTERHUB_CONFIG=/app/jupyterhub_config.py
    restart: unless-stopped
